version: '2'

services:
  mongo:
    image: bitnami/mongodb:3.6
    container_name: mongo
    networks:
      - backend
    environment:
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_DATABASE=db
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - 27017:27017
  
  app:
    image: astro-app
    container_name: app
    depends_on:
      - mongo 
    networks:
      - backend
      - frontend
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - frontend
    volumes:
      - ./app/templates/index.html:/usr/share/nginx/html/index.html
      - ./app/nginx.conf:/etc/nginx/nginx.conf
    

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data: