version: "3"

services:
  jenkins:
    image: myjenkins
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080'
      - '22:22'

volumes:
  jenkins_home: